#!/bin/bash
# @Author: Kenny Lindelof <contact@kennyl.tv>
# @Date:   2017-04-29 17:09:32
# @Last Modified by:   kennyL
# @Last Modified time: 2017-04-29 23:49:11
# @Repo: https://github.com/kennyLtv/SourceModUpdater

# Path to the 'serverfiles/csgo'
# example '/home/csgoserver/serverfiles/csgo'
DIR="csgoserverpathhere"
WORKING="UD_working"

#
# Please be sure to have the folling installed
# CuRL
# wget
#

# Working Directory For The Script
mkdir $WORKING
cd $WORKING

# Getting the latest SourceMod
#
# SM_CURRENT Give the current version of SourceMod
echo Retrieving Current SourceMod
echo
SM_CURRENT=`curl -s http://www.sourcemod.net/smdrop/1.10/sourcemod-latest-linux`
#Downloads the Current SM Version.
wget -q "http://www.sourcemod.net/smdrop/1.10/$SM_CURRENT"
#Extracting Current SM
tar -zxf $SM_CURRENT

## Getting the latest MetaMod
echo Retrieving Current Meta Mod
echo
MM_CURRENT=`curl -s http://metamodsource.net/mmsdrop/1.10/mmsource-latest-linux`
#Downloads the Current MetaMod Version.
wget -q "http://metamodsource.net/mmsdrop/1.10/$MM_CURRENT"
#Extracting MetaMod Source
tar -zxf $MM_CURRENT

echo Removing Extra Files
echo
# Removing Unwanted Files
rm -fr $SM_CURRENT addons/sourcemod/configs $MM_CURRENT

cd ../

echo Moving Files To Directories
echo

cp -R $WORKING/addons $DIR
cp -R $WORKING/cfg $DIR

rm -fr $WORKING

echo
echo
echo Looks like its completed
echo
echo Source Mod Version: $SM_CURRENT
echo Meta Mod Version: $MM_CURRENT
echo
